package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/jgero/hmc-datastore/graph/model"
)

// CreatePerson is the resolver for the createPerson field.
func (r *mutationResolver) CreatePerson(ctx context.Context, input model.NewPerson) (*model.Person, error) {
	return r.Repo.NewPerson(ctx, &input)
}

// UpdatePerson is the resolver for the updatePerson field.
func (r *mutationResolver) UpdatePerson(ctx context.Context, input model.UpdatePerson) (*model.Person, error) {
	return r.Repo.UpdatePerson(ctx, &input)
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*model.Post, error) {
	return r.Repo.NewPost(ctx, &input)
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input model.UpdatePost) (*model.Post, error) {
	return r.Repo.UpdatePost(ctx, &input)
}

// SetKeywords is the resolver for the setKeywords field.
func (r *mutationResolver) SetKeywords(ctx context.Context, input model.SetKeywords) ([]model.KeywordLink, error) {
	return r.Repo.WriteKeywords(ctx, &input)
}

// Keywords is the resolver for the keywords field.
func (r *personResolver) Keywords(ctx context.Context, obj *model.Person) ([]*model.Keyword, error) {
	return r.Repo.GetKeywordsForUuid(ctx, obj.UUID)
}

// Writer is the resolver for the writer field.
func (r *postResolver) Writer(ctx context.Context, obj *model.Post) (*model.Person, error) {
	return r.Repo.GetWriter(ctx, obj)
}

// Keywords is the resolver for the keywords field.
func (r *postResolver) Keywords(ctx context.Context, obj *model.Post) ([]*model.Keyword, error) {
	return r.Repo.GetKeywordsForUuid(ctx, obj.UUID)
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit int64, skip int64) ([]*model.Post, error) {
	return r.Repo.GetPosts(ctx, limit, skip)
}

// Keywords is the resolver for the keywords field.
func (r *queryResolver) Keywords(ctx context.Context) ([]*model.Keyword, error) {
	return r.Repo.GetKeywords(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Person returns PersonResolver implementation.
func (r *Resolver) Person() PersonResolver { return &personResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type personResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
