package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/jgero/hmc-datastore/graph/model"
	"github.com/jgero/hmc-datastore/graph/repository"
)

// Writer is the resolver for the writer field.
func (r *articleResolver) Writer(ctx context.Context, obj *model.Article) (*model.Person, error) {
	repo := repository.GetNeo4jRepo()
	return repo.GetWriter(ctx, obj)
}

// Keywords is the resolver for the keywords field.
func (r *articleResolver) Keywords(ctx context.Context, obj *model.Article) ([]string, error) {
	repo := repository.GetNeo4jRepo()
	return repo.GetKeywords(ctx, obj.Uuid)
}

// CreatePerson is the resolver for the createPerson field.
func (r *mutationResolver) CreatePerson(ctx context.Context, input model.NewPerson) (*model.Person, error) {
	repo := repository.GetNeo4jRepo()
	return repo.WritePerson(ctx, &input)
}

// CreateArticle is the resolver for the createArticle field.
func (r *mutationResolver) CreateArticle(ctx context.Context, input model.NewArticle) (*model.Article, error) {
	repo := repository.GetNeo4jRepo()
	return repo.WriteArticle(ctx, &input)
}

// Articles is the resolver for the articles field.
func (r *queryResolver) Articles(ctx context.Context) ([]*model.Article, error) {
	repo := repository.GetNeo4jRepo()
	return repo.GetArticles(ctx)
}

// Article returns ArticleResolver implementation.
func (r *Resolver) Article() ArticleResolver { return &articleResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type articleResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
